version: '3.8'

volumes:
  psql_data:

services:
  baton:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      memcached:
        condition: service_healthy
    build: 
      context: .
    ports:
      - 9062:9062
    command: >
      api
      --listen-addr=0.0.0.0:9062
      --network=custom
      --redis-uri=redis:6379
      --db=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
      --memcached-uris=memcached:11211
      --secret-key=$API_SK
      --seq-uri=$SEQ_URL
      --seq-chain-id=$SEQ_CHAIN_ID
      --seq-network-id=$SEQ_NETWORK_ID
      --seq-timeout=$SEQ_TIMEOUT
      --slot-future=$SLOT_FUTURE
      --loglevel=debug
    environment:
      - GENESIS_FORK_VERSION=0x00000000
      - GENESIS_VALIDATORS_ROOT=0x05a67bcb9b62c29b1fa06a5537c8e11684bf2ae9fbd683cae12e9b07e9e126d1
      - BELLATRIX_FORK_VERSION=0x00000000
      - CAPELLA_FORK_VERSION=0x00000000
      - DENEB_FORK_VERSION=0x00000000

  redis:
    image: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5

  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - '11211:11211'
    healthcheck:
      test: ["CMD-SHELL", "echo 'version' | nc -vn -w 1 memcached 11211 || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 5s

  db:
    image: postgres
    restart: always
    # uncomment following for database testing
    # ports:
    #   - 5432:5432
    volumes:
      - 'psql_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test:  [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8093:8080'
    environment:
      ADMINER_PLUGINS: tables-filter tinymce
