package migrations

import (
	"github.com/flashbots/mev-boost-relay/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration010CreateIncludedTobTxs = &migrate.Migration{
	Id: "010-create-included-tob-txs",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableIncludedTobTxs + ` (
			id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,
			slot            bigint NOT NULL,
			parent_hash varchar(66) NOT NULL,
			block_hash varchar(66) NOT NULL,
			tx_hash text NOT NULL
		);
 	`,
		``,
	},
	Down: []string{},

	DisableTransactionUp:   true,
	DisableTransactionDown: true,
}
