package migrations

import (
	"github.com/AnomalyFi/baton/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration012AddTobSubmitProfileTable = &migrate.Migration{
	Id: "012-create-tob-submit-profile",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableTobSubmitProfile + ` (
			id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,
			tx_hashes            text NOT NULL,
			parent_hash varchar(66) NOT NULL,
			slot varchar(66) NOT NULL,
			simulation_duration_us bigint NOT NULL default 0,

			tracer_duration_us bigint NOT NULL default 0,
			total_duration_us bigint NOT NULL default 0
	);
 	`,
		``,
	},
	Down: []string{},

	DisableTransactionUp:   true,
	DisableTransactionDown: true,
}
